
CREATE SCHEMA ESTUDIANTE;
CREATE SCHEMA ADMINISTRACION;
CREATE SCHEMA AUDITORIA;


CREATE TABLE AUDITORIA.tb_AUDITORIA
(
ID INT IDENTITY(1,1),
NOMBRE_TABLA VARCHAR (70),
ESTADO_ATENDIDA BIT NULL DEFAULT 0
)

CREATE TABLE ADMINISTRACION.tb_BECA
(
ID_BECA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TIPO_BECA VARCHAR(32),
IS_DELETED BIT NULL DEFAULT 0
);

CREATE TABLE ESTUDIANTE.tb_TELEFONO
(
ID_TELEFONO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NUMERO_TELEFONO VARCHAR(32),
IS_DELETED INT NULL DEFAULT 0
);

CREATE TABLE ADMINISTRACION.tb_CARRERA
(
ID_CARRERA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE_CARRERA VARCHAR(32),
IS_DELETED BIT NULL DEFAULT 0
);

CREATE TABLE ADMINISTRACION.tb_SEDE
(
ID_SEDE INT IDENTITY(1,1) PRIMARY KEY NOT  NULL,
NOMBRE_SEDE VARCHAR(32),
IS_DELETED BIT NULL DEFAULT 0
);

CREATE TABLE ESTUDIANTE.tb_DIRECCION
(
ID_DIRECCION INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
DETALLES VARCHAR(32),
IS_DELETED INT NULL DEFAULT 0
);

CREATE TABLE ESTUDIANTE.tb_ESTUDIANTE
(
ID_ESTUDIANTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE_ESTUDIANTE VARCHAR(32),
APELLIDOS_ESTUDIANTE VARCHAR(32),
EDAD INT,
PROMEDIO VARCHAR(32),
CARNE VARCHAR(32),
ID_DIRECCION_ESTUDIANTE INT,
IS_DELETED INT NULL DEFAULT 0
);

CREATE TABLE ADMINISTRACION.tb_CURSO
(
ID_CURSO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE_CURSO VARCHAR(32),
CREDITOS INT,
IS_DELETED INT NULL DEFAULT 0
);

CREATE TABLE ESTUDIANTE.tb_ESTUDIANTE_BECA
(
ID_ESTUDIANTE INT NOT NULL,
ID_BECA INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_BECA PRIMARY KEY (ID_ESTUDIANTE, ID_BECA),
IS_DELETED INT NULL DEFAULT 0
);

CREATE TABLE ESTUDIANTE.tb_ESTUDIANTE_TELEFONO
(
ID_ESTUDIANTE INT NOT NULL,
ID_TELEFONO INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_TELEFONO PRIMARY KEY (ID_ESTUDIANTE, ID_TELEFONO),
IS_DELETED INT NULL DEFAULT 0
);

CREATE TABLE ESTUDIANTE.tb_ESTUDIANTE_CARRERA
(
ID_ESTUDIANTE INT NOT NULL,
ID_CARRERA INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_CARRERA PRIMARY KEY (ID_ESTUDIANTE, ID_CARRERA),
IS_DELETED INT NULL DEFAULT 0
);

CREATE TABLE ESTUDIANTE.tb_ESTUDIANTE_SEDE
(
ID_ESTUDIANTE INT NOT NULL,
ID_SEDE INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_SEDE PRIMARY KEY (ID_ESTUDIANTE, ID_SEDE),
IS_DELETED INT NULL DEFAULT 0
);

CREATE TABLE ESTUDIANTE.tb_ESTUDIANTE_CURSO
(
ID_ESTUDIANTE INT NOT NULL,
ID_CURSO INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_CURSO PRIMARY KEY (ID_ESTUDIANTE, ID_CURSO),
IS_DELETED INT NULL DEFAULT 0
);