ALTER PROCEDURE AUDITORIA.sp_DISABLE_TRIGGER
AS
BEGIN
	BEGIN TRAN
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_DIRECCION] ON [ESTUDIANTE].[tb_DIRECCION];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE] ON [ESTUDIANTE].[tb_ESTUDIANTE];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_BECA] ON [ESTUDIANTE].[tb_ESTUDIANTE_BECA];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_CARRERA] ON [ESTUDIANTE].[tb_ESTUDIANTE_CARRERA];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_CURSO] ON [ESTUDIANTE].[tb_ESTUDIANTE_CURSO];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_SEDE] ON [ESTUDIANTE].[tb_ESTUDIANTE_SEDE];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_TELEFONO] ON [ESTUDIANTE].[tb_ESTUDIANTE_TELEFONO];');
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_TELEFONO] ON [ESTUDIANTE].[tb_TELEFONO];'); 
		-- DISABLE Trigger [tg_DIRECCION] ON [ESTUDIANTE].[tb_DIRECCION];
		-- DISABLE Trigger [tg_ESTUDIANTE] ON [ESTUDIANTE].[tb_ESTUDIANTE];
		-- DISABLE Trigger [tg_ESTUDIANTE_BECA] ON [ESTUDIANTE].[tb_ESTUDIANTE_BECA];
		-- DISABLE Trigger [tg_ESTUDIANTE_CARRERA] ON [ESTUDIANTE].[tb_ESTUDIANTE_CARRERA];
		-- DISABLE Trigger [tg_ESTUDIANTE_CURSO] ON [ESTUDIANTE].[tb_ESTUDIANTE_CURSO];
		-- DISABLE Trigger [tg_ESTUDIANTE_SEDE] ON [ESTUDIANTE].[tb_ESTUDIANTE_SEDE];
		-- DISABLE Trigger [tg_ESTUDIANTE_TELEFONO] ON [ESTUDIANTE].[tb_ESTUDIANTE_TELEFONO];
		-- DISABLE Trigger [tg_TELEFONO] ON [ESTUDIANTE].[tb_TELEFONO];
	COMMIT TRAN
END

CREATE PROCEDURE AUDITORIA.sp_ENABLE_TRIGGER
AS
BEGIN
	BEGIN TRAN
		 		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_DIRECCION] ON [ESTUDIANTE].[tb_DIRECCION];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE] ON [ESTUDIANTE].[tb_ESTUDIANTE];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_BECA] ON [ESTUDIANTE].[tb_ESTUDIANTE_BECA];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_CARRERA] ON [ESTUDIANTE].[tb_ESTUDIANTE_CARRERA];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_CURSO] ON [ESTUDIANTE].[tb_ESTUDIANTE_CURSO];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_SEDE] ON [ESTUDIANTE].[tb_ESTUDIANTE_SEDE];'); 
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_ESTUDIANTE_TELEFONO] ON [ESTUDIANTE].[tb_ESTUDIANTE_TELEFONO];');
		 EXEC('USE [db_proyecto_admin_est]; DISABLE Trigger [tg_TELEFONO] ON [ESTUDIANTE].[tb_TELEFONO];'); 
	COMMIT TRAN
END