CREATE PROCEDURE sp_INSERTAR_ESTUDIANTE
@param_NOMBRE_ESTUDIANTE VARCHAR(32),
@param_APELLIDOS_ESTUDIANTE VARCHAR(32),
@param_EDAD INT,
@param_PROMEDIO VARCHAR(32),
@param_CARNE VARCHAR(32)
AS
BEGIN

INSERT INTO tb_ESTUDIANTE VALUES

(
@param_NOMBRE_ESTUDIANTE,
@param_APELLIDOS_ESTUDIANTE,
@param_EDAD,
@param_PROMEDIO,
@param_CARNE
);

END

---------------------------------------------------------

CREATE PROCEDURE sp_INSERTAR_BECA
@param_TIPO_BECA INT
AS
BEGIN

INSERT INTO tb_BECA VALUES
(
@param_TIPO_BECA
);

END

---------------------------------------------------------

CREATE PROCEDURE sp_INSERTAR_CARRERA
@param_NOMBRE_CARRERA VARCHAR(32)
AS
BEGIN

INSERT INTO tb_CARRERA VALUES
(
@param_NOMBRE_CARRERA
)

END

---------------------------------------------------------

CREATE PROCEDURE sp_INSERTAR_CURSO
@param_NOMBRE_CURSO VARCHAR(32),
@param_CREDITOS INT
AS
BEGIN 

INSERT INTO tb_CURSO VALUES
(
 @param_NOMBRE_CURSO,
 @param_CREDITOS
);

END

--------------------------------------------------------

CREATE PROCEDURE sp_INSERTAR_SEDE
@param_NOMBRE_SEDE VARCHAR(32)
AS
BEGIN

INSERT INTO tb_SEDE VALUES
(
@param_NOMBRE_SEDE
);

END

--------------------------------------------------------
CREATE PROCEDURE sp_INSERTAR_TELEFONO_ESTUDIANTE
@param_NUMERO_TELEFONO VARCHAR(32),
@param_ID_ESTUDIANTE INT
AS

BEGIN

INSERT INTO tb_TELEFONO VALUES
(
@param_NUMERO_TELEFONO
)

DECLARE @local_ID_TELEFONO INT
SET @local_ID_TELEFONO=SCOPE_IDENTITY()

INSERT INTO tb_ESTUDIANTE_TELEFONO
(
@param_ID_ESTUDIANTE,
@local_ID_TELEFONO
)

END

---------------------------------------------------

CREATE PROCEDURE sp_INSERTAR_CURSO_ESTUDIANTE
@param_ID_ESTUDIANTE INT,
@param_ID_CURSO INT
AS

BEGIN 

INSERT INTO tb_ESTUDIANTE_CURSO VALUES
(
@param_ID_ESTUDIANTE,
@param_ID_CURSO
)
END
-------------------------------------------------

CREATE PROCEDURE sp_INSERTAR_CARRERA_ESTUDIANTE
@param_ID_ESTUDIANTE INT,
@param_NOMBRE_CARRERA VARCHAR(32)

AS

BEGIN 

INSERT INTO ESTUDIANTE_CARRERA VALUES
(
@param_ID_ESTUDIANTE,
@param_NOMBRE_CARRERA
)

END