
CREATE PROCEDURE ESTUDIANTE.sp_MOSTRAR_ESTUDIANTES
AS
BEGIN

	SELECT
	E.ID_ESTUDIANTE AS ID,
	E.NOMBRE_ESTUDIANTE AS NOMBRE,
	E.APELLIDOS_ESTUDIANTE AS APELLIDOS,
	E.EDAD AS EDAD,
	E.CARNE AS CARNE,
	E.PROMEDIO AS PROMEDIO,
	B.TIPO_BECA AS TIPO_BECA,
	S.NOMBRE_SEDE AS NOMBRE_SEDE,
	D.DETALLES AS DETALLES


	FROM ESTUDIANTE.tb_ESTUDIANTE E
		JOIN ESTUDIANTE.tb_ESTUDIANTE_BECA EB
		 ON E.ID_ESTUDIANTE=EB.ID_ESTUDIANTE
			JOIN ADMINISTRACION.tb_BECA B
			 ON B.ID_BECA=EB.ID_BECA
				JOIN ESTUDIANTE.tb_DIRECCION D
				 ON D.ID_DIRECCION=E.ID_DIRECCION_ESTUDIANTE
					JOIN ESTUDIANTE.tb_ESTUDIANTE_SEDE ES
					 ON ES.ID_ESTUDIANTE=E.ID_ESTUDIANTE
						JOIN ADMINISTRACION.tb_SEDE S
						 ON S.ID_SEDE=ES.ID_SEDE
						  WHERE E.IS_DELETED=0 AND ES.IS_DELETED=0 AND EB.IS_DELETED=0

END


CREATE PROCEDURE ESTUDIANTE.sp_MOSTRAR_ESTUDIANTES_POR_CARNE
@param_CARNE VARCHAR(32)
AS
BEGIN

	SELECT
	E.ID_ESTUDIANTE AS ID,
	E.NOMBRE_ESTUDIANTE AS NOMBRE,
	E.APELLIDOS_ESTUDIANTE AS APELLIDOS,
	E.EDAD AS EDAD,
	E.CARNE AS CARNE,
	E.PROMEDIO AS PROMEDIO,
	B.TIPO_BECA AS TIPO_BECA,
	S.NOMBRE_SEDE AS NOMBRE_SEDE,
	D.DETALLES AS DETALLES


	FROM ESTUDIANTE.tb_ESTUDIANTE E
		JOIN ESTUDIANTE.tb_ESTUDIANTE_BECA EB
		 ON E.ID_ESTUDIANTE=EB.ID_ESTUDIANTE
			JOIN ADMINISTRACION.tb_BECA B
			 ON B.ID_BECA=EB.ID_BECA
				JOIN ESTUDIANTE.tb_DIRECCION D
				 ON D.ID_DIRECCION=E.ID_DIRECCION_ESTUDIANTE
					JOIN ESTUDIANTE.tb_ESTUDIANTE_SEDE ES
					 ON ES.ID_ESTUDIANTE=E.ID_ESTUDIANTE
						JOIN ADMINISTRACION.tb_SEDE S
						 ON S.ID_SEDE=ES.ID_SEDE
						  WHERE E.IS_DELETED=0 AND ES.IS_DELETED=0 AND EB.IS_DELETED=0 AND E.CARNE=@param_CARNE

END

