
CREATE TABLE tb_ESTUDIANTE
(
ID_ESTUDIANTE INT PRIMARY KEY NOT NULL,
NOMBRE_ESTUDIANTE VARCHAR(32),
APELLIDOS_ESTUDIANTE VARCHAR(32),
PROMEDIO VARCHAR(32),
CARNE VARCHAR(32)
);

CREATE TABLE tb_BECA
(
ID_BECA INT PRIMARY KEY NOT NULL,
TIPO_BECA INT,
IS_DELETED BIT
);

CREATE TABLE tb_TELEFONO
(
ID_TELEFONO INT PRIMARY KEY NOT NULL,
NUMERO_TELEFONO VARCHAR(32),
IS_DELETED BIT
);

CREATE TABLE tb_CARRERA
(
ID_CARRERA INT PRIMARY KEY NOT NULL,
NOMBRE_CARRERA VARCHAR(32),
IS_DELETED BIT
);

CREATE TABLE tb_SEDE
(
ID_SEDE INT PRIMARY KEY NOT  NULL,
NOMBRE_SEDE VARCHAR(32),
IS_DELETED BIT
);

CREATE TABLE tb_DIRECCION
(
ID_DIRECCION INT PRIMARY KEY NOT NULL,
DETALLES VARCHAR(32),
IS_DELETED BIT
);

CREATE TABLE tb_CURSO
(
ID_CURSO INT PRIMARY KEY NOT NULL,
NOMBRE_CURSO VARCHAR(32),
CREDITOS INT,
IS_DELETED BIT
)

CREATE TABLE tb_ESTUDIANTE_BECA
(
ID_ESTUDIANTE INT NOT NULL,
ID_BECA INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_BECA PRIMARY KEY (ID_ESTUDIANTE, ID_BECA)
,CONSTRAINT FK_ID_ESTUDIANTE_B FOREIGN KEY (ID_ESTUDIANTE) REFERENCES tb_ESTUDIANTE (ID_ESTUDIANTE)
,CONSTRAINT FK_ID_BECA_E FOREIGN KEY (ID_BECA) REFERENCES tb_BECA (ID_BECA)
);

CREATE TABLE tb_ESTUDIANTE_TELEFONO
(
ID_ESTUDIANTE INT NOT NULL,
ID_TELEFONO INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_TELEFONO PRIMARY KEY (ID_ESTUDIANTE, ID_TELEFONO)
,CONSTRAINT FK_ID_ESTUDIANTE_T FOREIGN KEY (ID_ESTUDIANTE) REFERENCES tb_ESTUDIANTE (ID_ESTUDIANTE)
,CONSTRAINT FK_ID_TELEFONO_E FOREIGN KEY (ID_TELEFONO) REFERENCES tb_TELEFONO (ID_TELEFONO)
);

CREATE TABLE tb_ESTUDIANTE_CARRERA
(
ID_ESTUDIANTE INT NOT NULL,
ID_CARRERA INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_CARRERA PRIMARY KEY (ID_ESTUDIANTE, ID_CARRERA)
,CONSTRAINT FK_ID_ESTUDIANTE_C FOREIGN KEY (ID_ESTUDIANTE) REFERENCES tb_ESTUDIANTE (ID_ESTUDIANTE)
,CONSTRAINT FK_ID_CARRERA_E FOREIGN KEY (ID_CARRERA) REFERENCES tb_CARRERA (ID_CARRERA)
);

CREATE TABLE tb_ESTUDIANTE_SEDE
(
ID_ESTUDIANTE INT NOT NULL,
ID_SEDE INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_BECA PRIMARY KEY (ID_ESTUDIANTE, ID_SEDE)
,CONSTRAINT FK_ID_ESTUDIANTE_S FOREIGN KEY (ID_ESTUDIANTE) REFERENCES tb_ESTUDIANTE (ID_ESTUDIANTE)
,CONSTRAINT FK_ID_SEDE_E FOREIGN KEY (ID_SEDE) REFERENCES tb_SEDE (ID_SEDE)
);

CREATE TABLE tb_ESTUDIANTE_DIRECCION
(
ID_ESTUDIANTE INT NOT NULL,
ID_DIRECCION INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_BECA PRIMARY KEY (ID_ESTUDIANTE, ID_DIRECCION)
,CONSTRAINT FK_ID_ESTUDIANTE_D FOREIGN KEY (ID_ESTUDIANTE) REFERENCES tb_ESTUDIANTE (ID_ESTUDIANTE)
,CONSTRAINT FK_ID_DIRECCION_E FOREIGN KEY (ID_DIRECCION) REFERENCES tb_DIRECCION (ID_DIRECCION)
);

CREATE TABLE tb_ESTUDIANTE_CURSO
(
ID_ESTUDIANTE INT NOT NULL,
ID_CURSO INT NOT NULL,
CONSTRAINT PK_ESTUDIANTE_BECA PRIMARY KEY (ID_ESTUDIANTE, ID_CURSO)
,CONSTRAINT FK_ID_ESTUDIANTE_D FOREIGN KEY (ID_ESTUDIANTE) REFERENCES tb_ESTUDIANTE (ID_ESTUDIANTE)
,CONSTRAINT FK_ID_CURSO_E FOREIGN KEY (ID_CURSO) REFERENCES tb_CURSO (ID_CURSO)
);