INSERT INTO ADMINISTRACION.tb_BECA(TIPO_BECA)VALUES('5'),('4'),('3'),('2'),('1');
INSERT INTO ADMINISTRACION.tb_SEDE(NOMBRE_SEDE)VALUES('Limón'),('Guápiles'),('Turrialba'),('Rodrigo Facio');
INSERT INTO ADMINISTRACION.tb_CARRERA(NOMBRE_CARRERA)VALUES('Informática Empresarial'),('Estudios Sociales'),('Matemática'),('Agronomía');
INSERT INTO ADMINISTRACION.tb_CURSO(NOMBRE_CURSO, CREDITOS)VALUES('Lógica',4),('Matemática Discreta',3),('Programación I',4),('Cálculo I',4);

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ADMINISTRACION.tb_SEDE;
ALTER TABLE ADMINISTRACION.tb_SEDE AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM AUDITORIA.tb_AUDITORIA;
ALTER TABLE AUDITORIA.tb_AUDITORIA AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ESTUDIANTE.tb_ESTUDIANTE;
ALTER TABLE ESTUDIANTE.tb_ESTUDIANTE AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ESTUDIANTE.tb_ESTUDIANTE_SEDE;
ALTER TABLE ESTUDIANTE.tb_ESTUDIANTE_SEDE AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ESTUDIANTE.tb_ESTUDIANTE_TELEFONO;
ALTER TABLE ESTUDIANTE.tb_ESTUDIANTE_TELEFONO AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ESTUDIANTE.tb_ESTUDIANTE_CARRERA;
ALTER TABLE ESTUDIANTE.tb_ESTUDIANTE_CARRERA AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ESTUDIANTE.tb_ESTUDIANTE_BECA;
ALTER TABLE ESTUDIANTE.tb_ESTUDIANTE_BECA AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ESTUDIANTE.tb_DIRECCION;
ALTER TABLE ESTUDIANTE.tb_DIRECCION AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ESTUDIANTE.tb_ESTUDIANTE_CURSO;
ALTER TABLE ESTUDIANTE.tb_ESTUDIANTE_CURSO AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM ESTUDIANTE.tb_TELEFONO;
ALTER TABLE ESTUDIANTE.tb_TELEFONO AUTO_INCREMENT = 1;

sp_MARCAR_ATENDIDO