SELECT* FROM ESTUDIANTE.tb_DIRECCION;
SELECT* FROM ADMINISTRACION.tb_BECA;
SELECT* FROM ADMINISTRACION.tb_SEDE;
SELECT* FROM ADMINISTRACION.tb_CURSO;
SELECT* FROM ESTUDIANTE.tb_TELEFONO;
SELECT* FROM ESTUDIANTE.tb_ESTUDIANTE;

INSERT INTO ESTUDIANTE.tb_DIRECCION (DETALLES) VALUES ('Turrialba, Cartago');
INSERT INTO ESTUDIANTE.tb_ESTUDIANTE (NOMBRE_ESTUDIANTE,APELLIDOS_ESTUDIANTE,EDAD,PROMEDIO,CARNE,
ID_DIRECCION_ESTUDIANTE) VALUES ('Randall', 'Mora Sánchez',21,'90','B1234',1);
--------------
INSERT INTO ESTUDIANTE.tb_DIRECCION (DETALLES) VALUES ('San Pedro, San José');
INSERT INTO ESTUDIANTE.tb_ESTUDIANTE (NOMBRE_ESTUDIANTE,APELLIDOS_ESTUDIANTE,EDAD,PROMEDIO,CARNE,
ID_DIRECCION_ESTUDIANTE) VALUES ('Pedro', 'Aguilar Sanabria',19,'95','B3453',2)