DELIMITER $$
CREATE PROCEDURE ESTUDIANTE.sp_BORRAR_ESTUDIANTE
(
IN param_CARNE INT,
OUT msg INT
)

BEGIN

DECLARE local_ID_ESTUDIANTE INT;

IF EXISTS(SELECT ID_ESTUDIANTE FROM ESTUDIANTE.tb_ESTUDIANTE WHERE CARNE=param_CARNE) THEN

	SET local_ID_ESTUDIANTE= (SELECT ID_ESTUDIANTE FROM ESTUDIANTE.tb_ESTUDIANTE WHERE CARNE=param_CARNE);

	UPDATE ESTUDIANTE.tb_ESTUDIANTE SET IS_DELETED=1 WHERE ID_ESTUDIANTE=local_ID_ESTUDIANTE;
	UPDATE ESTUDIANTE.tb_ESTUDIANTE_BECA SET IS_DELETED=1 WHERE ID_ESTUDIANTE=local_ID_ESTUDIANTE;
	UPDATE ESTUDIANTE.tb_ESTUDIANTE_SEDE SET IS_DELETED=1 WHERE ID_ESTUDIANTE=local_ID_ESTUDIANTE;
	UPDATE ESTUDIANTE.tb_ESTUDIANTE_TELEFONO SET IS_DELETED=1 WHERE ID_ESTUDIANTE=local_ID_ESTUDIANTE;

	SELECT 1 INTO msg;
  
    
   ELSE

	  SELECT 0 INTO msg;

END IF;

END $$

-------------------------------------



CREATE PROCEDURE ADMINISTRACION.sp_BORRAR_SEDE
@param_ID_SEDE INT
AS

BEGIN

UPDATE ADMINISTRACION.tb_SEDE SET IS_DELETED=1 WHERE ID_SEDE=@param_ID_SEDE;

RETURN 1;

END

------------------------------------


CREATE PROCEDURE ADMINISTRACION.sp_BORRAR_CURSO
@param_ID_CURSO INT
AS
BEGIN

UPDATE ADMINISTRACION.tb_CURSO SET IS_DELETED=1 WHERE ID_CURSO=@param_ID_CURSO;

RETURN 1;

END

------------------------------------

CREATE PROCEDURE ADMINISTRACION.sp_BORRAR_CARRERA
@param_ID_CARRERA INT
AS
BEGIN

UPDATE ADMINISTRACION.tb_CARRERA SET IS_DELETED=1 WHERE ID_CARRERA=@param_ID_CARRERA;

RETURN 1;

END

------------------------------------


CREATE PROCEDURE ADMINISTRACION.sp_BORRAR_BECA
@param_ID_BECA INT
AS

BEGIN

UPDATE ADMINISTRACION.tb_BECA SET IS_DELETED=1 WHERE ID_BECA=@param_ID_BECA;

RETURN 1;

END

-----------------------------------

DELIMITER $$
CREATE  PROCEDURE AUDITORIA.sp_BORRAR_DATOS_TABLA
(
IN param_TABLA VARCHAR(70) 
)
BEGIN
SET @table_name1 = param_TABLA;

 ##reinicia el auto increment
SET @t2 =('ALTER TABLE',@table_name1,'AUTO_INCREMENT = 0');
 PREPARE stmt4 FROM @t2;
 EXECUTE stmt4;
 DEALLOCATE PREPARE stmt4;
 
 ##procede a eliminar los datos de la tabla
 
 SET sql_safe_updates=0;
 SET @t1 =CONCAT('DELETE FROM ',@table_name1);
 PREPARE stmt3 FROM @t1;
 EXECUTE stmt3;
 DEALLOCATE PREPARE stmt3;
 
END $$

