sp_MOSTRAR_CONTACTOS_ESTUDIANTE
DELIMITER $$
CREATE PROCEDURE ESTUDIANTE.sp_MOSTRAR_ESTUDIANTES()

BEGIN

	SELECT
	E.ID_ESTUDIANTE AS ID,
	E.NOMBRE_ESTUDIANTE AS NOMBRE,
	E.APELLIDOS_ESTUDIANTE AS APELLIDOS,
	E.EDAD AS EDAD,
	E.CARNE AS CARNE,
	E.PROMEDIO AS PROMEDIO,
	B.TIPO_BECA AS TIPO_BECA,
	S.NOMBRE_SEDE AS NOMBRE_SEDE,
	D.DETALLES AS DETALLES


	FROM ESTUDIANTE.tb_ESTUDIANTE E
		JOIN ESTUDIANTE.tb_ESTUDIANTE_BECA EB
		 ON E.ID_ESTUDIANTE=EB.ID_ESTUDIANTE
			JOIN ADMINISTRACION.tb_BECA B
			 ON B.ID_BECA=EB.ID_BECA
				JOIN ESTUDIANTE.tb_DIRECCION D
				 ON D.ID_DIRECCION=E.ID_DIRECCION_ESTUDIANTE
					JOIN ESTUDIANTE.tb_ESTUDIANTE_SEDE ES
					 ON ES.ID_ESTUDIANTE=E.ID_ESTUDIANTE
						JOIN ADMINISTRACION.tb_SEDE S
						 ON S.ID_SEDE=ES.ID_SEDE
						  WHERE E.IS_DELETED=0 AND ES.IS_DELETED=0 AND EB.IS_DELETED=0;

END$$

DELIMITER $$
CREATE PROCEDURE ESTUDIANTE.sp_MOSTRAR_ESTUDIANTES_POR_CARNE
(
IN param_CARNE VARCHAR(32)
)

BEGIN

	SELECT
	E.ID_ESTUDIANTE AS ID,
	E.NOMBRE_ESTUDIANTE AS NOMBRE,
	E.APELLIDOS_ESTUDIANTE AS APELLIDOS,
	E.EDAD AS EDAD,
	E.CARNE AS CARNE,
	E.PROMEDIO AS PROMEDIO,
	B.TIPO_BECA AS TIPO_BECA,
	S.NOMBRE_SEDE AS NOMBRE_SEDE,
	D.DETALLES AS DETALLES


	FROM ESTUDIANTE.tb_ESTUDIANTE E
		JOIN ESTUDIANTE.tb_ESTUDIANTE_BECA EB
		 ON E.ID_ESTUDIANTE=EB.ID_ESTUDIANTE
			JOIN ADMINISTRACION.tb_BECA B
			 ON B.ID_BECA=EB.ID_BECA
				JOIN ESTUDIANTE.tb_DIRECCION D
				 ON D.ID_DIRECCION=E.ID_DIRECCION_ESTUDIANTE
					JOIN ESTUDIANTE.tb_ESTUDIANTE_SEDE ES
					 ON ES.ID_ESTUDIANTE=E.ID_ESTUDIANTE
						JOIN ADMINISTRACION.tb_SEDE S
						 ON S.ID_SEDE=ES.ID_SEDE
						  WHERE E.IS_DELETED=0 AND ES.IS_DELETED=0 AND EB.IS_DELETED=0 AND E.CARNE=param_CARNE;

END$$

DELIMITER $$
CREATE PROCEDURE ESTUDIANTE.sp_MOSTRAR_CURSOS_ESTUDIANTE
(
IN param_ID_ESTUDIANTE INT
)


	BEGIN

	SELECT 
	C.ID_CURSO,
	C.NOMBRE_CURSO,
	C.CREDITOS

		FROM ESTUDIANTE.tb_ESTUDIANTE_CURSO EC
			JOIN ESTUDIANTE.tb_ESTUDIANTE E
	         ON EC.ID_ESTUDIANTE=E.ID_ESTUDIANTE
				JOIN ADMINISTRACION.tb_CURSO C
	             ON C.ID_CURSO=EC.ID_CURSO
					WHERE E.ID_ESTUDIANTE=param_ID_ESTUDIANTE AND EC.IS_DELETED=0;
	
END$$

DELIMITER $$
CREATE PROCEDURE ESTUDIANTE.sp_MOSTRAR_CARRERA_ESTUDIANTE
(
IN param_ID_ESTUDIANTE INT
)

BEGIN

	SELECT 

	   C.NOMBRE_CARRERA 
		FROM ADMINISTRACION.tb_CARRERA  C 
			JOIN ESTUDIANTE.tb_ESTUDIANTE_CARRERA EC 
		     ON  C.ID_CARRERA=EC.ID_CARRERA
			 WHERE EC.ID_ESTUDIANTE=param_ID_ESTUDIANTE AND EC.IS_DELETED=0;
END$$

DELIMITER $$
CREATE PROCEDURE ESTUDIANTE.sp_MOSTRAR_CONTACTOS_ESTUDIANTE
(
IN param_ID_ESTUDIANTE INT
)

BEGIN
	SELECT 
		T.NUMERO_TELEFONO 

			FROM ESTUDIANTE.tb_TELEFONO T 
				JOIN ESTUDIANTE.tb_ESTUDIANTE_TELEFONO ET 
	             ON T.ID_TELEFONO=ET.ID_TELEFONO
				 WHERE ET.ID_ESTUDIANTE=param_ID_ESTUDIANTE AND ET.IS_DELETED=0;
END$$

DELIMITER $$
CREATE PROCEDURE ADMINISTRACION.sp_MOSTRAR_BECAS ()
BEGIN

SELECT B.ID_BECA, B.TIPO_BECA FROM ADMINISTRACION.tb_BECA B WHERE B.IS_DELETED=0;
END$$

DELIMITER $$
CREATE PROCEDURE ADMINISTRACION.sp_MOSTRAR_CARRERAS ()
BEGIN
SELECT C.ID_CARRERA, C.NOMBRE_CARRERA FROM ADMINISTRACION.tb_CARRERA C WHERE C.IS_DELETED=0 ;
END $$

DELIMITER $$
CREATE PROCEDURE ADMINISTRACION.sp_MOSTRAR_CURSOS ()

	BEGIN

	SELECT 
	C.ID_CURSO,
	C.NOMBRE_CURSO,
	C.CREDITOS

		FROM ADMINISTRACION.tb_CURSO C WHERE C.IS_DELETED=0;
	             
END $$

DELIMITER $$
CREATE PROCEDURE ADMINISTRACION.sp_MOSTRAR_SEDES ()
BEGIN
SELECT S.ID_SEDE, S.NOMBRE_SEDE FROM ADMINISTRACION.tb_SEDE S WHERE S.IS_DELETED=0;
END $$