CREATE SCHEMA AUDITORIA;

CREATE TABLE AUDITORIA.tb_AUDITORIA
(
	 ID INT NOT NULL PRIMARY KEY auto_increment
    ,NOMBRE_TABLA VARCHAR(70)
    ,ESTADO_ATENDIDA BIT NULL DEFAULT 0
);

---------------

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_DIRECCION AFTER UPDATE ON ESTUDIANTE.tb_DIRECCION
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_DIRECCION', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_DIRECCION AFTER DELETE ON ESTUDIANTE.tb_DIRECCION
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_DIRECCION', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_DIRECCION AFTER INSERT ON ESTUDIANTE.tb_DIRECCION
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_DIRECCION', '1');
END;
END$$
DELIMITER ;

-------------

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE AFTER UPDATE ON ESTUDIANTE.tb_ESTUDIANTE
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE AFTER DELETE ON ESTUDIANTE.tb_ESTUDIANTE
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE AFTER INSERT ON ESTUDIANTE.tb_ESTUDIANTE
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE', '1');
END;
END$$
DELIMITER ;

-----------

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_BECA AFTER UPDATE ON ESTUDIANTE.tb_ESTUDIANTE_BECA
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_BECA', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_BECA AFTER DELETE ON ESTUDIANTE.tb_ESTUDIANTE_BECA
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_BECA', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_BECA AFTER INSERT ON ESTUDIANTE.tb_ESTUDIANTE_BECA
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_BECA', '1');
END;
END$$
DELIMITER ;

-------

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_CARRERA AFTER UPDATE ON ESTUDIANTE.tb_ESTUDIANTE_CARRERA
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_CARRERA', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_CARRERA AFTER DELETE ON ESTUDIANTE.tb_ESTUDIANTE_CARRERA
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_CARRERA', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_CARRERA AFTER INSERT ON ESTUDIANTE.tb_ESTUDIANTE_CARRERA
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_CARRERA', '1');
END;
END$$
DELIMITER ;

------

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_CURSO AFTER UPDATE ON ESTUDIANTE.tb_ESTUDIANTE_CURSO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_CURSO', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_CURSO AFTER DELETE ON ESTUDIANTE.tb_ESTUDIANTE_CURSO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_CURSO', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_CURSO AFTER INSERT ON ESTUDIANTE.tb_ESTUDIANTE_CURSO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_CURSO', '1');
END;
END$$
DELIMITER ;

-----

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_SEDE AFTER UPDATE ON ESTUDIANTE.tb_ESTUDIANTE_SEDE
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_SEDE', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_SEDE AFTER DELETE ON ESTUDIANTE.tb_ESTUDIANTE_SEDE
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_SEDE', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_SEDE AFTER INSERT ON ESTUDIANTE.tb_ESTUDIANTE_SEDE
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_SEDE', '1');
END;
END$$
DELIMITER ;

---

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_TELEFONO AFTER UPDATE ON ESTUDIANTE.tb_ESTUDIANTE_TELEFONO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_TELEFONO', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_TELEFONO AFTER DELETE ON ESTUDIANTE.tb_ESTUDIANTE_TELEFONO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_TELEFONO', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_ESTUDIANTE_TELEFONO AFTER INSERT ON ESTUDIANTE.tb_ESTUDIANTE_TELEFONO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_ESTUDIANTE_TELEFONO', '1');
END;
END$$
DELIMITER ;

---

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_TELEFONO AFTER UPDATE ON ESTUDIANTE.tb_TELEFONO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_TELEFONO', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_TELEFONO AFTER DELETE ON ESTUDIANTE.tb_TELEFONO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_TELEFONO', '1');
END;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER ESTUDIANTE.tg_TELEFONO AFTER INSERT ON ESTUDIANTE.tb_TELEFONO
FOR EACH ROW
BEGIN
	INSERT INTO AUDITORIA.tb_AUDITORIA(NOMBRE_TABLA, ESTADO_ATENDIDA) VALUES('ESTUDIANTE.tb_TELEFONO', '1');
END;
END$$
DELIMITER ;


